FROM ros:noetic-ros-base

RUN apt-get update && apt-get install -y \
    python3-pip python3-venv python3-dev \
    iproute2 iw wireless-tools net-tools iputils-ping \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
